### ISSUE TITLE
Invalid checksum generation

### ISSUE THREAD

**Issue by zcc39r** [ceridwen-com/ceridwen-standard-interchange-protocol-library#3]
Checksum has variable length (instead of fixed one of 4 chars) as leading zeros are stripped.

E.g.  `1804000120200130    135624AB0000185778|AH20181011|AJLe Français accéléré : Ускоренный курс французского языка (с фонограммой) / В.П. Филимонова : Учеб. пособие для школ, гимназий и колледжей  с франц. яз. в качестве  второго яз. и для самостоятельного изучения.|CF00000|AY2AZ9C9`

**Comment by mdovey** [comment]
Thanks for the patch, I've applied this to the upstream repository
